name    'gildas-homebrew'
version '0.4.11'
source 'https://github.com/gildas/puppet-homebrew'
author 'gildas'
license 'Apache License, Version 2.0'
summary 'Homebrew package installer and provider'
description 'Homebrew for Mac OS/X package installer and provider for PuppetLabs'
project_page 'https://github.com/gildas/puppet-homebrew'
